"""add profession to user

Revision ID: 6ecb6f7752d3
Revises: 740e8e2092eb
Create Date: 2026-07-28 13:56:42.397147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecb6f7752d3'
down_revision: Union[str, Sequence[str], None] = '740e8e2092eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profession', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profession')
    # ### end Alembic commands ###
